### ISSUE TITLE
Phantom 4 standard how to calibrate gimbal?

### ISSUE THREAD

**Issue by lrgc99** [o-gs/dji-firmware-tools#162] opened 2020-05-20 16:29 UTC
Hi,
is it possible to calibrate the gimbal of a standard phantom 4?
I tried:

 python comm_og_service_tool.py com(the right one) P4 GimbalCalib JointCoarse

He tells me he doesn't know the sleep command.
I tried to eliminate it but nothing.

Is there a particular syntax in this case?
Thanks so much!

**Comment by mefistotelis** [comment] 2021-03-10 08:12
Duplicate of:
https://github.com/o-gs/dji-firmware-tools/issues/99

**Closed by mefistotelis** 2021-03-10 08:12 UTC
