### ISSUE TITLE
Bricked Ambarella A9 firmware on Zenmuse X3

### ISSUE THREAD

**Issue by RingingResonance** [o-gs/dji-firmware-tools#281] opened 2022-07-05 00:24 UTC
While trying to fix another problem I was having, I ended up causing another problem where the A9 would boot up, function seemingly normally for about 17 seconds, and then boot loop. So I connected a serial port to it's serial IO and entered it's debug console by pressing ESC. There weren't many options here, but I tried doing 'diag nand etc.etc.' and it passed, but apparently it isn't documented that this also erases the NAND flash! >:(

So I found the two pads that need to be brought to ground to get it into USB boot mode and I've downloaded DirectUSB and AmbaUSB and tried them both with the extracted *.bin files. I can't get either to work. Has anyone else recovered a bricked A9 with this method?

I've already fixed my other problems that I can tell. I had to reflash the TI board. Info here: https://old.reddit.com/r/dji/comments/vphlcy/borked_firmware_on_inspire_1_remote_model_gl658a/

**Comment by mefistotelis** [comment] 2023-01-09 16:49
Closing as duplicate of #157

**Closed by mefistotelis** 2023-01-09 16:49 UTC
